* requires Java 1.5 or later and maven2
* command line:
	* go to the rega-genotype directory
	* mvn package
	* after the package procedure the target directory will contain a war and jar
* eclipse:
	* install eclipse-maven plugin:
		* update-site http://m2eclipse.sonatype.org/update/
			* Maven integration for Eclipse
			* (Maven Central repository index)
	* right click project -> Run as -> Maven package
	* after the package procedure the target directory will contain a war and jar
