BUILD
-----

Build instructions for rega-genotype.

* requires Java 1.5 or later and ant

* command line:
	* go to the rega-genotype directory
	* ant
	* the dist directory will contain a war and jar, if the build + test objects were executed correctly

* eclipse:
	* right click the build.xml -> Run as -> Ant build
	* the dist directory will contain a war and jar, if the build + test objects were executed correctly